### ISSUE TITLE
pulp test does not pass arguments to test programs correctly

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript-contrib/pulp#239]
Currently you can't pass psa flags to pulp test, ie:

`pulp test --stash --censor-lib --strict`

**Comment by hdgarrood** [comment]
The behaviour for passthrough args changed in 10.0, see the [changelog](https://github.com/bodil/pulp/blob/master/CHANGELOG.md#1000):

> Explicit separation of passthrough arguments (#220). The original behaviour that unrecognised arguments were passed through to psc (or whichever underlying program pulp calls) has turned out to be confusing. Instead, passthrough arguments are now separated from pulp's arguments with a --. Any unrecognised arguments before the -- will now cause pulp to complain.

You probably want `pulp test -- --stash --censor-lib --strict`.

**Comment by Risto-Stevcev** [comment]
That doesn't work:

```
> pulp test -- --censor-lib --strict --stash

* Building project in /home/pureuser/src
           Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  
* Build successful.
* Running tests...
node: bad option: --censor-lib
node: bad option: --strict
node: bad option: --stash
```

**Comment by Risto-Stevcev** [comment]
Oh, I see what's going on, it's passing that to node instead of psa because I'm running it via `npm test`. But I want to keep that functionality to avoid having to install psa globally (`npm test` and `npm run [cmd]` will look in `./node_modules/.bin` for binaries).

**Comment by Risto-Stevcev** [comment]
Actually, that error doesn't exist with `npm run build`:

```
> pulp build -- --censor-lib --strict --stash

* Building project in /home/pureuser/src
           Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  
* Build successful.
npm info lifecycle @~postbuild: @
npm info ok 
```

This is the package.json:

```json
{
  "private": true,
  "scripts": {
    "clean": "rimraf output && rimraf .pulp-cache",
    "build": "pulp build -- --censor-lib --strict --stash",
    "test": "pulp test -- --censor-lib --strict --stash"
  },
  "devDependencies": {
    "purescript-psa": "^0.4.0",
    "rimraf": "^2.5.0"
  }
}
```

**Comment by natefaubion** [comment]
I think it's passing it to node because pulp calls out to node to launch the tests. Pulp is not giving the extra arguments to psa/psc, but to node instead.

**Comment by natefaubion** [comment]
Here: https://github.com/bodil/pulp/blob/master/src/Pulp/Test.purs#L41

**Comment by hdgarrood** [comment]
Ok - then what you want to do is this:

```
pulp build -I test --to test.js --main Test.Main -- --strict --censor-lib --stash
node test.js
```

**Comment by hdgarrood** [comment]
Seems like pulp isn't passing args to the test program correctly though, we should fix that.

**Comment by mcoffin** [comment]
So this is due to how the `node` binary will stop parsing arguments after the first positional argument (presumably the script), but `pulp test` supplies the script inline with `node -e`, meaning node never hits a positional argument, and therefore keeps on trying to parse the remaining arguments as arguments to node itself rather than the script. Should be an easy fix; I'll whip up a PR.

FWIW though, node's manpage seems to indicate that this *isn't* how this is *supposed to work.

From node `v7.4.0`:
```
SYNOPSIS
       node [options] [v8 options] [script.js | -e "script"] [arguments]
       node debug [script.js | -e "script" | <host>:<port>] ...
       node [--v8-options]
```

**Comment by hdgarrood** [comment]
I released @mcoffin's fix in 10.0.1 just now. Thanks again!

**Comment by safareli** [comment]
with pulp@11.0.0
none of this work
```
$ pulp build -I test --to test.js --main Test.Main -- --censor-codes=UnusedExplicitImport
Invalid option `--censor-codes=UnusedExplicitImport'

Usage: purs COMMAND
  The PureScript compiler and tools
* ERROR: Subcommand terminated with exit code 1

$ ./node_modules/.bin/pulp build -- --censor-codes=UnusedExplicitImport
Invalid option `--censor-codes=UnusedExplicitImport'

Usage: purs COMMAND
  The PureScript compiler and tools
* ERROR: Subcommand terminated with exit code 1

```

`pulp test -- --censor-codes=UnusedExplicitImport` <- this executes but still getting `UnusedExplicitImport` warnings

**Comment by mcoffin** [comment]
I'll take a look at this later today if I have the time. is the `--censor-codes` options still valid in 0.11.x's `purs compile` command?

This probably also belongs in it's own issue, as it's about passing arguments to the actual compiler, rather than passing `argv` to the actual test program itself.

ping @safareli 

**EDIT**: I'm also going to be hanging out in `#purescript` on Freenode per usual so I'd be happy to help you out if you ping me on there.

**Comment by hdgarrood** [comment]
Yes, but only if you're using `psa`. If you want to use `--censor-codes` you have to make sure `psa` is installed, as before.

**Comment by hdgarrood** [comment]
Also, writing `pulp test -- --censor-codes=UnusedExplicitImport` will pass `--censor-codes=UnusedExplicitImport` to the test program, not the compiler frontend; that's why it works but you still see those warnings.

In case it's not clear, by "compiler frontend" I mean `psa` if it's installed or `purs` otherwise.

**Comment by hdgarrood** [comment]
That is, I think everything is working correctly and @safareli just needs to install `psa` if they want to use psa-specific options like --censor-codes.

**Comment by safareli** [comment]
I have psa installed:
```
  "devDependencies": {
    "pulp": "^11.0.0",
    "purescript": "^0.11.0",
    "purescript-psa": "^0.5.0",
    "rimraf": "^2.6.1"
  }
```

**Comment by hdgarrood** [comment]
If psa is installed locally you'll need to use `npm exec` or whatever the command is to make sure executables from local packages are on your PATH.
